config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: "users#index"
  
  resources :rooms, only: [:new, :create, :show]
   resources :messages, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :users, through: :user_rooms
  has_many :messages
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :motorcycle_model, presence: true  
  
has_many :user_rooms
has_many :rooms, through: :user_rooms
has_many :messages
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :motorcycle_model, :introduction])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
 
  def new
    @room = Room.new
  end

  def show
    @room = Room.find(params[:id])
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to @room
    else
      render :new
    end
  end


  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiderChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
       <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/new.html.erb
<header id="myHeader">
   <h1>Rider chat</h1>
 </header>
<body>
 <div class='chat-room-form'>
  <h1>新規チャットルーム作成</h1>
  

   <%= form_with model: @room, local: true, required: true do |f| %>
     <div class='chat-room-form__field'>
       <div class='chat-room-form__field--left'>
         <%= f.label :name, 'チャットルーム名', class: 'chat-room-form__label' %>
       </div>
       <div class='chat-room-form__field--right'>
         <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください' %>
       </div>
     </div>
     <div class='chat-room-form__field'>
       <div class='chat-room-form__field--left'></div>
       <div class='chat-room-form__field--right'>
         <%= f.submit '作成する', class: 'chat-room-form__action-btn' %>
       </div>
     </div>
    
   <% end %>
 </div>
</body>

app/views/rooms/show.html.erb
  <div class="chat-room-header">
    <h1><%= @room.name %></h1>
    <div class="chat-room-members">
      <% @room.users.each do |user| %>
        <span class="chat-room-member"><%= user.username %></span>
      <% end %>
    </div>
  </div>

  <div class="chat-room-messages">
    <% @room.messages.each do |message| %>
      <div class="chat-room-message">
        <span class="message-sender"><%= message.user.username %></span>
        <span class="message-content"><%= message.content %></span>
        <span class="message-timestamp"><%= message.created_at.strftime('%H:%M:%S') %></span>
      </div>
    <% end %>
  </div>

  <div class="chat-room-form">
    <%= form_for [@chat_room, Message.new] do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: "form-control", placeholder: "Type your message here..." %>
      </div>
      <div class="form-group">
        <%= f.submit "Send", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Rider chat</title>
		<link rel="stylesheets" href="style.css">
	</head>
	<body>
	
		<header id="myHeader">
			<h1>Rider chat</h1>
     <% if user_signed_in? %>
			 <ul class="button-list">
				<li><%= link_to 'チャットを始める', new_room_path %></li>
				<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
			 </ul>
		 <% else %> 
				<ul class="button-list">
					<li><%= link_to 'ログイン', new_user_session_path %></li>
					<li><%= link_to '新規登録', new_user_registration_path %></li>
				</ul>
     <% end %>
			</div>
		
		</header>
		<div class="bg-image"></div>
		<footer>
			<p>Copyright © 2023 riderchat</p>
		</footer>
	</body>
</html>

app/views/users/show.html.erb
<head>
  <title><%= @user.name %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'profile', media: 'all' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<div class="user-profile">
  <h2><%= @user.name %>のプロフィール</h2>
  <p>メールアドレス: <%= @user.email %></p>
  <p>バイクのモデル: <%= @user.motorcycle_model %></p>
  <p>自己紹介: <%= @user.introduction %></p>

  <% if current_user != @user %>
    <% if current_user.following?(@user) %>
      <%= button_to "フォロー中", unfollow_user_path(@user), method: :post %>
    <% else %>
      <%= button_to "フォローする", follow_user_path(@user), method: :post %>
    <% end %>
  <% else %>
    <%= link_to "編集", edit_user_path(@user) %>
  <% end %>
</div>